apiVersion: v1
kind: Service
metadata:
  name: {{ include "gophprofile.fullname" . }}-{{ .Values.worker.name }}
  labels:
    {{- include "gophprofile.componentLabels" (dict "component" .Values.worker.name "Release" .Release "Chart" .Chart) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "gophprofile.selectorLabels" (dict "component" .Values.worker.name "Release" .Release "Chart" .Chart) | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.worker.metricsPort }}
      targetPort: metrics
      protocol: TCP
